name: Deploy Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ${{ secrets.VPS_PATH }}
            docker compose --env-file .env.vps -f docker-compose.vps.yml pull frontend
            docker compose --env-file .env.vps -f docker-compose.vps.yml up -d frontend
            docker compose --env-file .env.vps -f docker-compose.vps.yml ps
